In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

import numpy as np
import pandas as pd
from estimate_R_KF_adj import parametrized_estimation

In [3]:
# defines if delays, generation time distribution or both should be adjusted
variations = ["", "_delays", "_GTD"]

# sources of parameters
methods = [
    "_ETH",
    "_RKI",
    "_Ilmenau",
    "_SDSC",
    "_Zi",
    "_AGES",
    "_epiforecasts",
    "_rtlive",
    "_globalrt",
]

input_folder = "D:/EllasDaten/Uni/Wirtschaftsingenieurwesen/6Semester/Bachelorarbeit/Code/Rt_estimate_reconstruction/ArroyoMarioli/input_output_dataset/"
output_folder = "D:/EllasDaten/Uni/Wirtschaftsingenieurwesen/6Semester/Bachelorarbeit/Code/Rt_estimate_reconstruction/ArroyoMarioli/estimates/"

In [4]:
# run all estimations

# for variation in variations:
#     for method in methods:
#         parametrized_estimation(variation, method, data_source="_rtlive", input_folder=input_folder, output_folder=output_folder)

In [7]:
# run estimation with original globalrt parameters and data used by rtlive and originally in this method, respecitvely

parametrized_estimation(variation="", method="_globalrt", data_source="_rtlive", input_folder=input_folder, output_folder=output_folder)

parametrized_estimation(variation="", method="_globalrt", data_source="", input_folder=input_folder, output_folder=output_folder)

globalrt estimation with parameters from globalrt and data used by rtlive
smoothed
[0.18111214 0.17097593 0.16277468 0.1561931  0.15095095]
filtered
[0.51383718 0.36492118 0.30092002 0.26452619 0.24120985]
globalrt estimation with parameters from globalrt and data used by original method
smoothed
[0.16303137 0.15161739 0.14303895 0.13667884 0.13201889]
filtered
[0.40623363 0.28942899 0.24034147 0.2133641  0.19682913]
smoothed
[0.19719583 0.18943358 0.18267052 0.17680009 0.17172285]
filtered
[0.67925935 0.48123582 0.39467934 0.34415684 0.31064692]
smoothed
[0.06416661 0.0641666  0.0641666  0.06416659 0.06416659]
filtered
[1.49933743 1.06019169 0.86564289 0.74966874 0.67052411]


In [10]:
estimates_adjusted_input_data = pd.read_csv(output_folder + "estimated_R_globalrt_data_from_rtlive.csv")
estimates_adjusted_input_data.head()

Country/Region        Date         R      se_R  days_infectious   ci_95_u  \
0        Germany  2020-03-04  4.782051  0.000000                4  4.782051   
1        Germany  2020-03-05  3.144161  0.000021                4  3.144203   
2        Germany  2020-03-06  2.125479  0.000000                4  2.125479   
3        Germany  2020-03-07  1.230323  0.000021                4  1.230365   
4        Germany  2020-03-08  0.766506  0.000021                4  0.766548   

    ci_95_l   ci_50_u   ci_50_l  
0  4.782051  4.782051  4.782051  
1  3.144119  3.144175  3.144146  
2  2.125479  2.125479  2.125479  
3  1.230281  1.230338  1.230309  
4  0.766464  0.766520  0.766491

In [5]:
estimates_adjusted_input_data = pd.read_csv(output_folder + "estimated_R_globalrt_data_from_rtlive.csv")
estimates_adjusted_input_data.head()

Country/Region        Date         R      se_R  days_infectious   ci_95_u  \
0        Germany  2020-03-04  2.569774  0.181112                4  2.924747   
1        Germany  2020-03-05  2.530785  0.170976                4  2.865892   
2        Germany  2020-03-06  2.480986  0.162775                4  2.800019   
3        Germany  2020-03-07  2.437453  0.156193                4  2.743586   
4        Germany  2020-03-08  2.415194  0.150951                4  2.711052   

    ci_95_l   ci_50_u   ci_50_l  
0  2.214801  2.691932  2.447616  
1  2.195678  2.646107  2.415464  
2  2.161954  2.590776  2.371196  
3  2.131320  2.542803  2.332102  
4  2.119335  2.517009  2.313379

In [11]:
estimates_original_input_data = pd.read_csv(output_folder + "estimated_R_globalrt_data_from.csv")
estimates_original_input_data.head()

Country/Region        Date         R      se_R  days_infectious   ci_95_u  \
0        Austria  2020-03-09  2.064775  0.163031                4  2.384311   
1        Austria  2020-03-10  2.096212  0.151617                4  2.393377   
2        Austria  2020-03-11  2.125103  0.143039                4  2.405454   
3        Austria  2020-03-12  2.151174  0.136679                4  2.419059   
4        Austria  2020-03-13  2.197820  0.132019                4  2.456572   

    ci_95_l   ci_50_u   ci_50_l  
0  1.745239  2.174738  1.954812  
1  1.799047  2.198476  1.993948  
2  1.844751  2.221581  2.028624  
3  1.883288  2.243362  2.058985  
4  1.939068  2.286865  2.108775

In [12]:
parametrized_estimation(variation="_GTD", method="_globalrt", data_source="_rtlive", input_folder=input_folder, output_folder=output_folder)

globalrt estimation with GTD from globalrt and data used by rtlive


In [13]:
parametrized_estimation(variation="_window", method="_globalrt", data_source="_rtlive", input_folder=input_folder, output_folder=output_folder)

globalrt estimation with window from globalrt and data used by rtlive
